"""second iteration: student account, remove recitation/evaluation, point-performance link

Revision ID: a89fda91c31a
Revises: d69fb0ac8fd6
Create Date: 2026-08-24 10:58:28.538372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89fda91c31a'
down_revision: Union[str, Sequence[str], None] = 'd69fb0ac8fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_student_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_recitations_id'), table_name='recitations')
    op.drop_index(op.f('ix_recitations_student_id'), table_name='recitations')
    op.drop_table('recitations')
    with op.batch_alter_table('points') as batch_op:
        batch_op.add_column(sa.Column('performance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_points_performance', 'performances', ['performance_id'], ['id'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    with op.batch_alter_table('points') as batch_op:
        batch_op.drop_constraint('fk_points_performance', type_='foreignkey')
        batch_op.drop_column('performance_id')
    op.create_table('recitations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recitations_student_id'), 'recitations', ['student_id'], unique=False)
    op.create_index(op.f('ix_recitations_id'), 'recitations', ['id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('grade', sa.VARCHAR(length=5), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_student_id'), 'evaluations', ['student_id'], unique=False)
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    # ### end Alembic commands ###
